services:
  - type: web
    name: online-exam-server
    env: node
    buildCommand: echo "Build starting..." && npm install && echo "NPM install done" && npx babel src -d dist && echo "Babel done" && node verify.js && echo "Verify done"
    startCommand: node test-start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false 