services:
  - type: web
    name: online-exam-server
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: node dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false 